# theme: jekyll-theme-slate
permalink: pretty
title: mrrobust - Stata package for two-sample Mendelian randomization analyses
email: tom.palmer@lancaster.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Stata package for two-sample Mendelian randomization analyses
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: remlapmot

# Build settings
markdown: kramdown
theme: minima
